/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.viatra.dse.validation;

import org.eclipse.viatra.dse.validation.AbstractDdslValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class DdslValidator extends AbstractDdslValidator {
}
