/*
 * generated by Xtext 2.10.0
 */
package org.eclipse.viatra.dse.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDdslScopeProvider extends DelegatingScopeProvider {
}
