<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="org.eclipse.viatra.dse.dsl.dseexecutionmodel"
    nsPrefix="model">
  <eClassifiers xsi:type="ecore:EClass" name="DseExecutionModel" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="packageName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="configurations" upperBound="-1"
        eType="#//Configuration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dseproblems" upperBound="-1"
        eType="#//DseProblem"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dseproblemcomponents" upperBound="-1"
        eType="#//DseProblemComponent"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfRuns" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DseProblem" eSuperTypes="#//DseImport">
    <eStructuralFeatures xsi:type="ecore:EReference" name="configurations" lowerBound="1"
        eType="#//Configuration" eOpposite="#//Configuration/dseproblems"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
        eType="#//Constraint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initialmodel" lowerBound="1"
        eType="#//InitialModel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metamodel" lowerBound="1"
        eType="#//MetaModel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectives" lowerBound="1"
        upperBound="-1" eType="#//BaseObjective"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transformationrules" lowerBound="1"
        upperBound="-1" eType="#//TransformationRule"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statecoder" eType="#//StateCoder"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="solutionstore" eType="#//SolutionStore"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Configuration" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dseproblems" upperBound="-1"
        eType="#//DseProblem" eOpposite="#//DseProblem/configurations"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxNumberOfThreads" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="strategy" lowerBound="1"
        eType="#//BaseStrategy"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Strategy" eSuperTypes="#//BaseStrategy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="depth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="-1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//StrategyType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constraint" eSuperTypes="#//DseProblemComponent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="constraintName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InitialModel" eSuperTypes="#//DseProblemComponent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MetaModel" eSuperTypes="#//DseProblemComponent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaseObjective" eSuperTypes="#//DseProblemComponent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fitnessConstraint" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comparator" eType="#//Comparators"
        defaultValueLiteral="HIGHER_IS_BETTER"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TransformationRule" eSuperTypes="#//DseProblemComponent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="className" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="methodName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DseProblemComponent" abstract="true"
      eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="StateCoder" eSuperTypes="#//DseProblemComponent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstraintsObjective" eSuperTypes="#//BaseObjective">
    <eStructuralFeatures xsi:type="ecore:EReference" name="softConstraints" upperBound="-1"
        eType="#//QueryConstraint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hardConstraints" upperBound="-1"
        eType="#//QueryConstraint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ModelQueryType">
    <eLiterals name="MUST_HAVE_MATCH"/>
    <eLiterals name="NO_MATCH" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Comparators">
    <eLiterals name="HIGHER_IS_BETTER"/>
    <eLiterals name="LOWER_IS_BETTER" value="1"/>
    <eLiterals name="DIFFERENCE_TO_ZERO_IS_BETTER" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QueryConstraint" eSuperTypes="#//Constraint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="weight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//ModelQueryType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SolutionStore" eSuperTypes="#//DseProblemComponent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="foundSolutions" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="acceptAnySolutions" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="storeBestSolutionsOnly"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="logSolutionsWhenFound"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="registerSolutionFoundHandler"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="StrategyType">
    <eLiterals name="DfsStrategy"/>
    <eLiterals name="BfsStrategy"/>
    <eLiterals name="FixedPriorityStrategy" value="2"/>
    <eLiterals name="HillClimbingStrategy" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DseImport" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="imports" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EvolutionaryStrategyBuilder" eSuperTypes="#//BaseStrategy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="populationSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="crossOvers" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//EvolutionStrategyType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mutations" upperBound="-1"
        eType="#//IMutationRate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IMutationRate" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="weight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EvolutionStrategyType">
    <eLiterals name="Nsga2"/>
    <eLiterals name="Pesa" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="DomainModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" upperBound="-1" eType="#//Type"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaseStrategy" abstract="true" eSuperTypes="#//Type"/>
</ecore:EPackage>
