/**
 *
 * $Id$
 */
package org.eclipse.viatra.dse.dsl.model.validation;


/**
 * A sample validator interface for {@link org.eclipse.viatra.dse.dsl.model.SolutionStore}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SolutionStoreValidator {
	boolean validate();

	boolean validateFoundSolutions(int value);
	boolean validateAcceptAnySolutions(boolean value);
	boolean validateStoreBestSolutionsOnly(boolean value);
	boolean validateLogSolutionsWhenFound(boolean value);
	boolean validateRegisterSolutionFoundHandler(boolean value);
	boolean validateName(String value);
}
