/**
 *
 * $Id$
 */
package org.eclipse.viatra.dse.dsl.model.validation;

import org.eclipse.viatra.dse.dsl.model.StrategyType;

/**
 * A sample validator interface for {@link org.eclipse.viatra.dse.dsl.model.Strategy}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface StrategyValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateDepth(int value);
	boolean validateType(StrategyType value);
}
