/*
 * generated by Xtext 2.10.0
 */
package org.eclipse.viatra.dse.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.viatra.dse.services.DdslGrammarAccess;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class DdslSyntacticSequencer extends AbstractSyntacticSequencer {

	protected DdslGrammarAccess grammarAccess;
	protected AbstractElementAlias match_BaseObjective_Impl_ColonKeyword_3_q;
	protected AbstractElementAlias match_DseProblem_SemicolonKeyword_3_4_q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (DdslGrammarAccess) access;
		match_BaseObjective_Impl_ColonKeyword_3_q = new TokenAlias(false, true, grammarAccess.getBaseObjective_ImplAccess().getColonKeyword_3());
		match_DseProblem_SemicolonKeyword_3_4_q = new TokenAlias(false, true, grammarAccess.getDseProblemAccess().getSemicolonKeyword_3_4());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_BaseObjective_Impl_ColonKeyword_3_q.equals(syntax))
				emit_BaseObjective_Impl_ColonKeyword_3_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_DseProblem_SemicolonKeyword_3_4_q.equals(syntax))
				emit_DseProblem_SemicolonKeyword_3_4_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     ':'?
	 *
	 * This ambiguous syntax occurs at:
	 *     name=ID (ambiguity) ';' (rule end)
	 *     name=ID (ambiguity) comparator=Comparators
	 *     name=ID (ambiguity) fitnessConstraint=EDouble
	 */
	protected void emit_BaseObjective_Impl_ColonKeyword_3_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ';'?
	 *
	 * This ambiguous syntax occurs at:
	 *     imports+=EString (ambiguity) 'Configuration' ':' configurations=[Configuration|EString]
	 *     imports+=EString (ambiguity) 'Constraint' ':' constraints+=[Constraint|ID]
	 *     imports+=EString (ambiguity) 'InitialModel' ':' initialmodel=[InitialModel|ID]
	 *     imports+=EString (ambiguity) 'MetaModel' ':' metamodel=[MetaModel|EString]
	 *     imports+=EString (ambiguity) 'objectives' ':' objectives+=[BaseObjective|EString]
	 */
	protected void emit_DseProblem_SemicolonKeyword_3_4_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
