/*
 * generated by Xtext 2.10.0
 */
package org.eclipse.viatra.dse.dsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class DslRuntimeModule extends org.eclipse.viatra.dse.AbstractDslRuntimeModule {
}
