/*
 * generated by Xtext 2.10.0
 */
package org.eclipse.viatra.dse.dsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class DslStandaloneSetup extends org.eclipse.viatra.dse.DslStandaloneSetupGenerated {

	def static void doSetup() {
		new DslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
