/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.viatra.dse.ui;

import com.google.inject.Binder;
import com.google.inject.binder.AnnotatedBindingBuilder;
import com.google.inject.binder.ScopedBindingBuilder;
import javax.inject.Singleton;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.viatra.dse.generator.DseOutputConfigurationProvider;
import org.eclipse.viatra.dse.ui.AbstractDdslUiModule;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.eclipse.xtext.generator.IOutputConfigurationProvider;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class DdslUiModule extends AbstractDdslUiModule {
  @Override
  public void configure(final Binder binder) {
    super.configure(binder);
    AnnotatedBindingBuilder<IOutputConfigurationProvider> _bind = binder.<IOutputConfigurationProvider>bind(IOutputConfigurationProvider.class);
    ScopedBindingBuilder _to = _bind.to(DseOutputConfigurationProvider.class);
    _to.in(Singleton.class);
  }
  
  public DdslUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
