/*
 * generated by Xtext 2.10.0
 */
package org.eclipse.viatra.dse.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.viatra.dse.parser.antlr.internal.InternalDdslParser;
import org.eclipse.viatra.dse.services.DdslGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class DdslParser extends AbstractAntlrParser {

	@Inject
	private DdslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalDdslParser createParser(XtextTokenStream stream) {
		return new InternalDdslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "DomainModel";
	}

	public DdslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DdslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
