/*
 * generated by Xtext 2.10.0
 */
package org.eclipse.viatra.dse.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class DdslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/eclipse/viatra/dse/parser/antlr/internal/InternalDdsl.tokens");
	}
}
