/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.viatra.dse;

import org.eclipse.viatra.dse.AbstractDdslRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class DdslRuntimeModule extends AbstractDdslRuntimeModule {
}
