/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.viatra.dse;

import org.eclipse.viatra.dse.DdslStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class DdslStandaloneSetup extends DdslStandaloneSetupGenerated {
  public static void doSetup() {
    DdslStandaloneSetup _ddslStandaloneSetup = new DdslStandaloneSetup();
    _ddslStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
